"""WebThings Gateway Constants."""


class MessageType:
    """Enumeration of IPC message types."""

    # Plugin messages
    PLUGIN_REGISTER_REQUEST = 0x0000
    PLUGIN_REGISTER_RESPONSE = 0x0001
    PLUGIN_UNLOAD_REQUEST = 0x0002
    PLUGIN_UNLOAD_RESPONSE = 0x0003
    PLUGIN_ERROR_NOTIFICATION = 0x0004

    # Adapter messages
    ADAPTER_ADDED_NOTIFICATION = 0x1000
    ADAPTER_UNLOAD_REQUEST = 0x1001
    ADAPTER_UNLOAD_RESPONSE = 0x1002
    ADAPTER_START_PAIRING_COMMAND = 0x1003
    ADAPTER_CANCEL_PAIRING_COMMAND = 0x1004
    ADAPTER_PAIRING_PROMPT_NOTIFICATION = 0x1005
    ADAPTER_UNPAIRING_PROMPT_NOTIFICATION = 0x1006
    ADAPTER_REMOVE_DEVICE_REQUEST = 0x1007
    ADAPTER_REMOVE_DEVICE_RESPONSE = 0x1008
    ADAPTER_CANCEL_REMOVE_DEVICE_COMMAND = 0x1009

    # Device messages
    DEVICE_ADDED_NOTIFICATION = 0x2000
    DEVICE_SET_PIN_REQUEST = 0x2001
    DEVICE_SET_PIN_RESPONSE = 0x2002
    DEVICE_SET_CREDENTIALS_REQUEST = 0x2003
    DEVICE_SET_CREDENTIALS_RESPONSE = 0x2004
    DEVICE_CONNECTED_STATE_NOTIFICATION = 0x2005
    DEVICE_SET_PROPERTY_COMMAND = 0x2006
    DEVICE_PROPERTY_CHANGED_NOTIFICATION = 0x2007
    DEVICE_EVENT_NOTIFICATION = 0x2008
    DEVICE_ACTION_STATUS_NOTIFICATION = 0x2009
    DEVICE_REMOVE_ACTION_REQUEST = 0x200A
    DEVICE_REMOVE_ACTION_RESPONSE = 0x200B
    DEVICE_REQUEST_ACTION_REQUEST = 0x200C
    DEVICE_REQUEST_ACTION_RESPONSE = 0x200D
    DEVICE_DEBUG_COMMAND = 0x200E

    # Notifier messages
    NOTIFIER_ADDED_NOTIFICATION = 0x3000
    NOTIFIER_UNLOAD_REQUEST = 0x3001
    NOTIFIER_UNLOAD_RESPONSE = 0x3002

    # Outlet messages
    OUTLET_ADDED_NOTIFICATION = 0x4000
    OUTLET_REMOVED_NOTIFICATION = 0x4001
    OUTLET_NOTIFY_REQUEST = 0x4002
    OUTLET_NOTIFY_RESPONSE = 0x4003

    # API handler messages
    API_HANDLER_ADDED_NOTIFICATION = 0x5000
    API_HANDLER_UNLOAD_REQUEST = 0x5001
    API_HANDLER_UNLOAD_RESPONSE = 0x5002
    API_HANDLER_API_REQUEST = 0x5003
    API_HANDLER_API_RESPONSE = 0x5004

    # Mock adapter messages
    MOCK_ADAPTER_ADD_DEVICE_REQUEST = 0xF000
    MOCK_ADAPTER_ADD_DEVICE_RESPONSE = 0xF001
    MOCK_ADAPTER_REMOVE_DEVICE_REQUEST = 0xF002
    MOCK_ADAPTER_REMOVE_DEVICE_RESPONSE = 0xF003
    MOCK_ADAPTER_PAIR_DEVICE_COMMAND = 0xF004
    MOCK_ADAPTER_UNPAIR_DEVICE_COMMAND = 0xF005
    MOCK_ADAPTER_CLEAR_STATE_REQUEST = 0xF006
    MOCK_ADAPTER_CLEAR_STATE_RESPONSE = 0xF007


class NotificationLevel:
    """Enumeration of notification levels."""

    LOW = 0
    NORMAL = 1
    HIGH = 2


DONT_RESTART_EXIT_CODE = 100
